### PR TITLE
Adapter Pattern

### PR DESCRIPTION
**Pull request by OleksiyAlsaadi**
Adapter Pattern for Stack using Stack Wrapper

### CODE REVIEW

**Comment by kbuffardi** [comment]
While the Wrapper class has wrapped the Stack class, you've had to create the functionality of Stack from scratch. That defeats the purpose of leveraging a wrapper class, which is meant to take advantage of an existing class and "wrapping" it with an improved public interface.

If you want to revise this pull request by leveraging existing class(es) and having the Stack class implement a new interface on a delegated instance, just push to this same fork with the revisions. Also, please don't delete the existing file (Stack.h) because it already demonstrates one design pattern solution to the problem. If there are conflicts, just go with a different file name.

**Comment by kbuffardi** [comment]
Sorry, I should have been clearer. `Stack.h` was another student's solution (that already implements a design pattern itself by delegating the std::list class) so your solution should be unique from it. 

In other words, if you provide your own stack solution that takes advantage of delegating an existing class (besides list, which has been done already), make your own .h file and this repo will have multiple different solutions.

**Comment by OleksiyAlsaadi** [comment]
Hopefully StackWrapper.h fulfills the requirements. I use a deque from stl and delegate a Stack class to it. There is a second class named StackWrapper that wraps the functions of the Stack class without modifying code.

**Comment by kbuffardi** [comment]
your Deque Stack looks pretty good. The Stack Wrapper class indeed wraps the Deque Stack but is unnecessary because the Deque Stack already accomplished the delegated "wrapping"

**Comment by kbuffardi** [comment]
Good work!

**Pull request merged**
